### ISSUE TITLE
Why not publish this project to npm registry?

### ISSUE THREAD

**Issue by Lucifier129** [tqma113/farrow-session#2]
Why not publish this project to npm registry?

**Comment by tqma113** [comment]
I find there are some room for improvement. Should it alawys set cookie to browser whether it has been changed? or only set cookie to browser when it has been changed? How to recongize it has been changed? The current practice is to reset at any time.

**Comment by tqma113** [comment]
Should I publish it first? or after finish this problem?

**Comment by Lucifier129** [comment]
In my opinion, it can be published first since it works. And improving it later:)

**Comment by tqma113** [comment]
Published https://www.npmjs.com/package/farrow-session 🎉
